# Generated by Django 5.1.4 on 2025-03-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='batch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='campName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='contractName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='hospitalName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='old_emp_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='prevcontractName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='batch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='campName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='contractName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='hospitalName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='old_emp_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='prevcontractName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='emp_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
