# Generated by Django 5.1.4 on 2025-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TextField(max_length=225),
        ),
    ]
