# Generated by Django 5.1.7 on 2025-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='aadhar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
