# Generated by Django 5.1.4 on 2025-02-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
