# Generated by Django 5.1.4 on 2025-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0002_dashboard_batch_dashboard_campname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='area',
            new_name='permanent_area',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='nationality',
            new_name='permanent_nationality',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='state',
            new_name='permanent_state',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='residential_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='residential_nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='residential_state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
