# Generated by Django 5.1.4 on 2025-04-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0002_alter_employee_details_aadhar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockDashboard',
        ),
        migrations.DeleteModel(
            name='MockEmployeeDetails',
        ),
        migrations.AddField(
            model_name='consultation',
            name='special_cases',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
