# Generated by Django 5.1.4 on 2025-02-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0002_delete_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking_yes_no', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Smoking (Yes/No)')),
                ('smoking_years', models.IntegerField(blank=True, null=True, verbose_name='Smoking Years')),
                ('smoking_per_day', models.IntegerField(blank=True, null=True, verbose_name='Smoking Per Day')),
                ('alcohol_yes_no', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Alcohol (Yes/No)')),
                ('alcohol_years', models.IntegerField(blank=True, null=True, verbose_name='Alcohol Years')),
                ('alcohol_frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alcohol Frequency')),
                ('paan_yes_no', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Paan (Yes/No)')),
                ('paan_years', models.IntegerField(blank=True, null=True, verbose_name='Paan Years')),
                ('diet', models.CharField(blank=True, choices=[('mixed', 'Mixed'), ('veg', 'Pure Veg'), ('egg', 'Eggetarian')], max_length=20, null=True, verbose_name='Diet')),
                ('medical_conditions_comments', models.TextField(blank=True, null=True, verbose_name='Medical Conditions Comments')),
                ('obstetric', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obstetric History')),
                ('gynecological', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gynecological History')),
                ('surgical_comments', models.TextField(blank=True, null=True, verbose_name='Surgical Comments')),
                ('num_children', models.IntegerField(default=0, verbose_name='Number of Children')),
                ('drug_allergy', models.BooleanField(default=False, verbose_name='Drug Allergy')),
                ('drug_allergy_comments', models.TextField(blank=True, null=True, verbose_name='Drug Allergy Comments')),
                ('food_allergy', models.BooleanField(default=False, verbose_name='Food Allergy')),
                ('food_allergy_comments', models.TextField(blank=True, null=True, verbose_name='Food Allergy Comments')),
                ('other_allergies', models.BooleanField(default=False, verbose_name='Other Allergies')),
                ('other_allergies_comments', models.TextField(blank=True, null=True, verbose_name='Other Allergies Comments')),
                ('father_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Status')),
                ('father_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Reason (if deceased)')),
                ('father_remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Remarks')),
                ('paternal_grand_father_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paternal Grandfather Status')),
                ('paternal_grand_father_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paternal Grandfather Reason (if deceased)')),
                ('paternal_grand_father_remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paternal Grandfather Remarks')),
                ('paternal_grand_mother_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paternal Grandmother Status')),
                ('paternal_grand_mother_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paternal Grandmother Reason (if deceased)')),
                ('paternal_grand_mother_remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paternal Grandmother Remarks')),
                ('mother_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Status')),
                ('mother_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Reason (if deceased)')),
                ('mother_remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Remarks')),
                ('maternal_grand_father_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maternal Grandfather Status')),
                ('maternal_grand_father_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maternal Grandfather Reason (if deceased)')),
                ('maternal_grand_father_remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maternal Grandfather Remarks')),
                ('maternal_grand_mother_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maternal Grandmother Status')),
                ('maternal_grand_mother_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maternal Grandmother Reason (if deceased)')),
                ('maternal_grand_mother_remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maternal Grandmother Remarks')),
                ('HTN_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='HTN Condition Details')),
                ('DM_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='DM Condition Details')),
                ('Epileptic_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Epileptic Condition Details')),
                ('Hyperthyroid_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hyperthyroid Condition Details')),
                ('Hypothyroid_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hypothyroid Condition Details')),
                ('Asthma_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asthma Condition Details')),
                ('CVS', models.CharField(blank=True, max_length=255, null=True, verbose_name='CVS Details')),
                ('CNS', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNS Details')),
                ('RS', models.CharField(blank=True, max_length=255, null=True, verbose_name='RS Details')),
                ('GIT', models.CharField(blank=True, max_length=255, null=True, verbose_name='GIT Details')),
                ('KUB', models.CharField(blank=True, max_length=255, null=True, verbose_name='KUB Details')),
                ('CANCER_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cancer Details')),
                ('OTHERS_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Medical Details')),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Submitted By')),
                ('booked_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booked To')),
            ],
            options={
                'verbose_name_plural': 'Medical Histories',
            },
        ),
    ]
