# Generated by Django 5.1.4 on 2025-02-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CTReport',
        ),
        migrations.DeleteModel(
            name='OccupationalProfile',
        ),
        migrations.DeleteModel(
            name='XRayReport',
        ),
    ]
