# Generated by Django 5.1.4 on 2025-04-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0003_delete_mockdashboard_delete_mockemployeedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='special_cases',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
