# Generated by Django 5.1.4 on 2025-02-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0004_delete_ctreport_delete_occupationalprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OthersTest',
        ),
        migrations.DeleteModel(
            name='WomensPack',
        ),
    ]
