# Generated by Django 5.1.4 on 2025-03-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0004_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
