# Generated by Django 5.1.4 on 2025-04-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0004_fitnessassessment_special_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='spouse_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
