# Generated by Django 5.1.4 on 2025-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0005_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=255)),
                ('employee_id', models.TextField(blank=True, max_length=100)),
                ('organization', models.TextField(max_length=255)),
                ('aadhar_no', models.TextField(max_length=225)),
                ('contractor_name', models.TextField(max_length=255)),
                ('purpose', models.TextField()),
                ('appointment_date', models.DateField()),
                ('date', models.DateField()),
                ('time', models.TextField(max_length=225)),
                ('booked_by', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('initiate', 'Initiate'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='initiate', max_length=20)),
            ],
        ),
    ]
