# Generated by Django 5.1.4 on 2025-04-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0005_medicalhistory_spouse_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='spouse_data',
            new_name='spouses_data',
        ),
    ]
