# Generated by Django 5.1.4 on 2025-03-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0005_medicalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='submission_details',
        ),
    ]
