# Generated by Django 5.1.4 on 2025-04-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0006_rename_spouse_data_medicalhistory_spouses_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='spouses_data',
            new_name='spouse_data',
        ),
    ]
