# Generated by Django 5.1.4 on 2025-03-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0006_remove_medicalhistory_submission_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignificantNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('healthsummary', models.TextField(blank=True, null=True, verbose_name='Health Summary')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('communicable_disease', models.CharField(blank=True, choices=[('CD1', 'CD1'), ('CD2', 'CD2'), ('Unknown', 'Unknown'), ('', 'Select...')], default='', max_length=50, null=True, verbose_name='Communicable Disease')),
                ('incident_type', models.CharField(blank=True, choices=[('FAC', 'Fac'), ('LTI', 'LTI'), ('MTC', 'MTC'), ('FATAL', 'Fatal'), ('', 'Select...')], default='', max_length=50, null=True, verbose_name='Incident Type')),
                ('incident', models.CharField(blank=True, choices=[('Occupational Injury', 'Occupational Injury'), ('Domestic Injury', 'Domestic Injury'), ('Communication Injury', 'Communication Injury'), ('Other Injury', 'Other Injury'), ('', 'Select...')], default='', max_length=100, null=True, verbose_name='Incident')),
                ('illness_type', models.CharField(blank=True, choices=[('Occupational Illness', 'Occupational Illness'), ('Occupational Disease', 'Occupational Disease'), ('', 'Select...')], default='', max_length=100, null=True, verbose_name='Illness Type')),
            ],
            options={
                'verbose_name': 'Significant Note',
                'verbose_name_plural': 'Significant Notes',
            },
        ),
    ]
