# Generated by Django 5.1.4 on 2025-02-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0007_fitnessassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessassessment',
            name='emp_no',
            field=models.CharField(max_length=20),
        ),
    ]
