# Generated by Django 5.1.4 on 2025-03-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0007_significantnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='significantnotes',
            name='healthsummary',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='significantnotes',
            name='remarks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
