# Generated by Django 5.1.4 on 2025-04-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0007_rename_spouses_data_medicalhistory_spouse_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discardedmedicine',
            name='discarded_date',
        ),
    ]
