# Generated by Django 5.1.4 on 2025-02-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0008_alter_fitnessassessment_emp_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.TextField(max_length=200)),
                ('type', models.TextField(max_length=255)),
                ('type_of_visit', models.TextField(max_length=255)),
                ('register', models.TextField(max_length=255)),
                ('purpose', models.TextField(max_length=255)),
            ],
        ),
    ]
