# Generated by Django 5.1.4 on 2025-03-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0008_rename_identification_marks_employee_details_identification_marks1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
