# Generated by Django 5.1.4 on 2025-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0008_alter_significantnotes_healthsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
