# Generated by Django 5.2 on 2025-12-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0009_alter_pharmacymedicine_chemical_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discardedmedicine',
            name='total_quantity',
        ),
    ]
