# Generated by Django 5.1.4 on 2025-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0009_employee_details_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignificantNotes',
        ),
        migrations.AddField(
            model_name='form17',
            name='emp_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form27',
            name='emp_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form38',
            name='emp_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form39',
            name='emp_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form40',
            name='emp_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
