# Generated by Django 5.1.4 on 2025-04-24 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0009_autoimmunetest_ctreport_occupationalprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystockhistory',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
