# Generated by Django 5.1.4 on 2025-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0009_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
