# Generated by Django 5.1.4 on 2025-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0010_delete_significantnotes_form17_emp_no_form27_emp_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='fc',
            field=models.FileField(blank=True, null=True, upload_to='fc/'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='manual/'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='report/'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='self_declared',
            field=models.FileField(blank=True, null=True, upload_to='self_declared/'),
        ),
    ]
