# Generated by Django 5.1.4 on 2025-04-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0010_alter_pharmacystockhistory_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcalibration',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pharmacymedicine',
            name='medicine_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Creams', 'Creams'), ('Lotions', 'Lotions'), ('Powder', 'Powder'), ('Respules', 'Respules'), ('Drops', 'Drops'), ('Fluids', 'Fluids'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacystock',
            name='medicine_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Creams', 'Creams'), ('Drops', 'Drops'), ('Fluids', 'Fluids'), ('Other', 'Other'), ('Lotions', 'Lotions'), ('Powder', 'Powder'), ('Respules', 'Respules')], max_length=20),
        ),
    ]
