# Generated by Django 5.2 on 2025-12-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0010_remove_discardedmedicine_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulanceconsumables',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='wardconsumables',
            name='total_quantity',
        ),
    ]
