# Generated by Django 5.1.4 on 2025-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0010_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mrd_no',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
