# Generated by Django 5.1.4 on 2025-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0010_dashboard_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('normal_doses', models.JSONField(default=dict)),
                ('booster_doses', models.JSONField(default=dict)),
            ],
        ),
    ]
