# Generated by Django 5.1.4 on 2025-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0011_vitals_fc_vitals_manual_vitals_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('medicine_form', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(max_length=255)),
                ('dose_volume', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('reason', models.TextField()),
                ('discarded_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('instrument_name', models.CharField(max_length=255)),
                ('numbers', models.IntegerField()),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_sl_no', models.CharField(blank=True, max_length=255, null=True)),
                ('calibration_date', models.DateField()),
                ('calibration_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignificantNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('emp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('healthsummary', models.JSONField(blank=True, default=list, null=True)),
                ('remarks', models.JSONField(blank=True, default=list, null=True)),
                ('communicable_disease', models.CharField(blank=True, choices=[('CD1', 'CD1'), ('CD2', 'CD2'), ('Unknown', 'Unknown'), ('', 'Select...')], default='', max_length=50, null=True, verbose_name='Communicable Disease')),
                ('incident_type', models.CharField(blank=True, choices=[('FAC', 'Fac'), ('LTI', 'LTI'), ('MTC', 'MTC'), ('FATAL', 'Fatal'), ('', 'Select...')], default='', max_length=50, null=True, verbose_name='Incident Type')),
                ('incident', models.CharField(blank=True, choices=[('Occupational Injury', 'Occupational Injury'), ('Domestic Injury', 'Domestic Injury'), ('Communication Injury', 'Communication Injury'), ('Other Injury', 'Other Injury'), ('', 'Select...')], default='', max_length=100, null=True, verbose_name='Incident')),
                ('illness_type', models.CharField(blank=True, choices=[('Occupational Illness', 'Occupational Illness'), ('Occupational Disease', 'Occupational Disease'), ('', 'Select...')], default='', max_length=100, null=True, verbose_name='Illness Type')),
            ],
            options={
                'verbose_name': 'Significant Note',
                'verbose_name_plural': 'Significant Notes',
            },
        ),
        migrations.CreateModel(
            name='WardConsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('medicine_form', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(max_length=255)),
                ('dose_volume', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('consumed_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.RenameField(
            model_name='expiryregister',
            old_name='item_name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='pharmacystock',
            old_name='item_name',
            new_name='brand_name',
        ),
        migrations.RemoveField(
            model_name='pharmacystock',
            name='removed_month',
        ),
        migrations.AddField(
            model_name='expiryregister',
            name='chemical_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form17',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form27',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form38',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form39',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form40',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='chemical_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='total_quantity',
            field=models.PositiveIntegerField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='drops',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='fluids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issued_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='syrups',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expiryregister',
            name='removed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PharmacyMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('medicine_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Creams', 'Creams'), ('Drops', 'Drops'), ('Fluids', 'Fluids'), ('Other', 'Other')], max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(max_length=255)),
                ('dose_volume', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('brand_name', 'chemical_name', 'dose_volume')},
            },
        ),
    ]
