# Generated by Django 5.1.4 on 2025-04-25 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0011_instrumentcalibration_entry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceConsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('medicine_form', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(max_length=255)),
                ('dose_volume', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('consumed_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
