# Generated by Django 5.1.4 on 2025-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0011_appointment_mrd_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultated_by',
            field=models.TextField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='contractor_name',
            field=models.TextField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.TextField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization_name',
            field=models.TextField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
