# Generated by Django 5.1.4 on 2025-04-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0012_discardedmedicine_instrumentcalibration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form17',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='form27',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='form38',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='form39',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='form40',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='instrumentcalibration',
            name='entry_date',
        ),
    ]
