# Generated by Django 5.1.4 on 2025-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0012_appointment_consultated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandcamps',
            name='camp_type',
            field=models.TextField(default='Upcoming', max_length=100),
        ),
    ]
