# Generated by Django 5.1.4 on 2025-03-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0013_alter_eventsandcamps_camp_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
