# Generated by Django 5.1.4 on 2025-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0013_remove_form17_entry_date_remove_form27_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='country_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
