# Generated by Django 5.1.4 on 2025-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0013_remove_ctreport_ct_abdomen_reference_range_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ambulance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='shifting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='shifting_required',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
