# Generated by Django 5.1.4 on 2025-04-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0014_consultation_ambulance_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='conditionalotherJobNature',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='otherJobNature',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
