# Generated by Django 5.1.4 on 2025-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0014_delete_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_history', models.JSONField(blank=True, null=True)),
                ('medical_data', models.JSONField(blank=True, null=True)),
                ('female_worker', models.JSONField(blank=True, null=True)),
                ('surgical_history', models.JSONField(blank=True, null=True)),
                ('family_history', models.JSONField(blank=True, null=True)),
                ('health_conditions', models.JSONField(blank=True, null=True)),
                ('submission_details', models.JSONField(blank=True, null=True)),
                ('allergy_fields', models.JSONField(blank=True, null=True)),
                ('allergy_comments', models.JSONField(blank=True, null=True)),
                ('children_data', models.JSONField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
