# Generated by Django 5.1.4 on 2025-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0014_employee_details_country_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='significantnotes',
            options={'ordering': ['-entry_date', 'emp_no'], 'verbose_name': 'Significant Note', 'verbose_name_plural': 'Significant Notes'},
        ),
        migrations.RemoveField(
            model_name='coagulationtest',
            name='bleeding_time_reference_range',
        ),
        migrations.RemoveField(
            model_name='coagulationtest',
            name='clotting_time_reference_range',
        ),
        migrations.RemoveField(
            model_name='coagulationtest',
            name='prothrombin_time_reference_range',
        ),
        migrations.RemoveField(
            model_name='coagulationtest',
            name='pt_inr_reference_range',
        ),
        migrations.RemoveField(
            model_name='culturesensitivitytest',
            name='blood_reference_range',
        ),
        migrations.RemoveField(
            model_name='culturesensitivitytest',
            name='motion_reference_range',
        ),
        migrations.RemoveField(
            model_name='culturesensitivitytest',
            name='sputum_reference_range',
        ),
        migrations.RemoveField(
            model_name='culturesensitivitytest',
            name='urine_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='acid_phosphatase_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='adenosine_deaminase_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='amylase_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='cpk_mb_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='cpk_total_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='ecg_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='echo_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='lipase_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='tmt_normal_reference_range',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='troponin_t_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='basophil_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='eosinophil_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='esr_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='hemoglobin_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='lymphocyte_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='mch_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='mchc_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='mcv_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='monocyte_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='neutrophil_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='pcv_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='platelet_count_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='rdw_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='total_rbc_reference_range',
        ),
        migrations.RemoveField(
            model_name='heamatalogy',
            name='total_wbc_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='calcium_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='chol_hdl_ratio_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='hdl_cholesterol_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='ldl_cholesterol_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='ldl_hdl_ratio_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='triglycerides_reference_range',
        ),
        migrations.RemoveField(
            model_name='lipidprofile',
            name='vldl_cholesterol_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='alb_glob_ratio_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='albumin_serum_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='alkaline_phosphatase_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='bilirubin_direct_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='bilirubin_indirect_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='bilirubin_total_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='gamma_glutamyl_transferase_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='globulin_serum_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='sgot_ast_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='sgpt_alt_reference_range',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='total_protein_reference_range',
        ),
        migrations.RemoveField(
            model_name='menspack',
            name='psa_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='appearance_motion_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='colour_motion_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='cyst_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='mucus_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='occult_blood_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='others_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='ova_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='pus_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='motiontest',
            name='rbcs_reference_range',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='mri_abdomen_reference_range',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='mri_brain_reference_range',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='mri_lungs_reference_range',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='mri_pelvis_reference_range',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='mri_spine_reference_range',
        ),
        migrations.RemoveField(
            model_name='ophthalmicreport',
            name='color_vision_reference_range',
        ),
        migrations.RemoveField(
            model_name='ophthalmicreport',
            name='vision_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='bun_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='calcium_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='chloride_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='phosphorus_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='potassium_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='serum_creatinine_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='sodium_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='urea_reference_range',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='uric_acid_reference_range',
        ),
        migrations.RemoveField(
            model_name='routinesugartests',
            name='estimated_average_glucose_reference_range',
        ),
        migrations.RemoveField(
            model_name='routinesugartests',
            name='glucose_f_reference_range',
        ),
        migrations.RemoveField(
            model_name='routinesugartests',
            name='glucose_pp_reference_range',
        ),
        migrations.RemoveField(
            model_name='routinesugartests',
            name='hba1c_reference_range',
        ),
        migrations.RemoveField(
            model_name='routinesugartests',
            name='random_blood_sugar_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='cyst_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='mucus_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='occult_blood_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='others_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='ova_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='pus_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='rbcs_reference_range',
        ),
        migrations.RemoveField(
            model_name='serologytest',
            name='screening_hiv_reference_range',
        ),
        migrations.RemoveField(
            model_name='thyroidfunctiontest',
            name='t3_reference_range',
        ),
        migrations.RemoveField(
            model_name='thyroidfunctiontest',
            name='t4_reference_range',
        ),
        migrations.RemoveField(
            model_name='thyroidfunctiontest',
            name='tsh_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='appearance_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='bacteria_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='bile_pigments_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='bile_salts_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='casts_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='colour_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='crystals_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='epithelial_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='glucose_urine_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='ketone_bodies_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='protein_albumin_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='reaction_ph_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='red_blood_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='specific_gravity_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='urobilinogen_reference_range',
        ),
        migrations.RemoveField(
            model_name='urineroutinetest',
            name='wbc_pus_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='usgreport',
            name='usg_abdomen_reference_range',
        ),
        migrations.RemoveField(
            model_name='usgreport',
            name='usg_kub_reference_range',
        ),
        migrations.RemoveField(
            model_name='usgreport',
            name='usg_neck_reference_range',
        ),
        migrations.RemoveField(
            model_name='usgreport',
            name='usg_pelvis_reference_range',
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='bleeding_time_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='bleeding_time_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='clotting_time_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='clotting_time_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='prothrombin_time_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='prothrombin_time_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='pt_inr_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='pt_inr_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='blood_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='blood_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='motion_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='motion_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='sputum_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='sputum_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='urine_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='urine_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='acid_phosphatase_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='acid_phosphatase_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='adenosine_deaminase_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='adenosine_deaminase_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='amylase_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='amylase_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='cpk_mb_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='cpk_mb_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='cpk_total_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='cpk_total_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='ecg_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='ecg_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='echo_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='echo_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='lipase_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='lipase_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='tmt_normal_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='tmt_normal_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='troponin_t_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='troponin_t_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='basophil_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='basophil_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='eosinophil_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='eosinophil_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='esr_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='esr_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='hemoglobin_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='hemoglobin_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='lymphocyte_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='lymphocyte_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mch_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mch_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mchc_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mchc_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mcv_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mcv_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='monocyte_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='monocyte_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='neutrophil_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='neutrophil_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='pcv_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='pcv_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='platelet_count_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='platelet_count_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='rdw_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='rdw_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='total_rbc_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='total_rbc_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='total_wbc_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='total_wbc_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='calcium_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='calcium_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='chol_hdl_ratio_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='chol_hdl_ratio_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='hdl_cholesterol_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='hdl_cholesterol_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='ldl_cholesterol_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='ldl_cholesterol_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='ldl_hdl_ratio_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='ldl_hdl_ratio_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='triglycerides_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='triglycerides_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='vldl_cholesterol_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='vldl_cholesterol_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='alb_glob_ratio_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='alb_glob_ratio_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='albumin_serum_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='albumin_serum_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='alkaline_phosphatase_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='alkaline_phosphatase_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='bilirubin_direct_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='bilirubin_direct_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='bilirubin_indirect_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='bilirubin_indirect_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='bilirubin_total_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='bilirubin_total_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='gamma_glutamyl_transferase_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='gamma_glutamyl_transferase_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='globulin_serum_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='globulin_serum_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='sgot_ast_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='sgot_ast_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='sgpt_alt_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='sgpt_alt_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='total_protein_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='total_protein_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menspack',
            name='psa_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menspack',
            name='psa_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='appearance_motion_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='appearance_motion_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='colour_motion_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='colour_motion_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='cyst_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='cyst_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='mucus_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='mucus_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='occult_blood_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='occult_blood_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='others_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='others_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='ova_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='ova_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='pus_cells_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='pus_cells_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='rbcs_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='rbcs_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_abdomen_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_abdomen_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_brain_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_brain_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_lungs_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_lungs_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_pelvis_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_pelvis_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_spine_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_spine_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmicreport',
            name='color_vision_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmicreport',
            name='color_vision_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmicreport',
            name='vision_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmicreport',
            name='vision_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='bun_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='bun_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='calcium_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='calcium_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='chloride_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='chloride_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='phosphorus_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='phosphorus_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='potassium_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='potassium_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='serum_creatinine_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='serum_creatinine_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='sodium_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='sodium_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='urea_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='urea_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='uric_acid_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='uric_acid_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='estimated_average_glucose_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='estimated_average_glucose_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='glucose_f_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='glucose_f_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='glucose_pp_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='glucose_pp_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='hba1c_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='hba1c_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='random_blood_sugar_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='random_blood_sugar_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='cyst_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='cyst_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='mucus_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='mucus_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='occult_blood_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='occult_blood_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='others_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='others_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='ova_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='ova_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='pus_cells_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='pus_cells_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='rbcs_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='rbcs_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='screening_hiv_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='screening_hiv_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='t3_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='t3_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='t4_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='t4_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='tsh_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='tsh_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='appearance_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='appearance_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='bacteria_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='bacteria_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='bile_pigments_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='bile_pigments_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='bile_salts_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='bile_salts_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='casts_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='casts_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='colour_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='colour_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='crystals_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='crystals_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='epithelial_cells_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='epithelial_cells_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='glucose_urine_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='glucose_urine_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='ketone_bodies_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='ketone_bodies_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='protein_albumin_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='protein_albumin_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='reaction_ph_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='reaction_ph_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='red_blood_cells_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='red_blood_cells_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='specific_gravity_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='specific_gravity_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='urobilinogen_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='urobilinogen_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='wbc_pus_cells_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='wbc_pus_cells_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_abdomen_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_abdomen_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_kub_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_kub_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_neck_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_neck_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_pelvis_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='usg_pelvis_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='conditional_fit_feilds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
