# Generated by Django 5.1.4 on 2025-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0015_alter_significantnotes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
