# Generated by Django 5.1.4 on 2025-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0015_fitnessassessment_conditionalotherjobnature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='submittedDoctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
