# Generated by Django 5.1.4 on 2025-03-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0016_vaccination_emo_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='emo_no',
            new_name='emp_no',
        ),
    ]
