# Generated by Django 5.1.4 on 2025-04-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0016_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='entry_date',
        ),
    ]
