# Generated by Django 5.1.4 on 2025-04-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0017_remove_member_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
