# Generated by Django 5.1.4 on 2025-05-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0017_remove_consultation_submitted_by_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='mrd_no',
            new_name='mrdNo',
        ),
        migrations.AddField(
            model_name='consultation',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form40',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
