# Generated by Django 5.1.4 on 2025-03-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0017_rename_emo_no_vaccination_emp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
