# Generated by Django 5.1.4 on 2025-04-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0018_member_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact_number',
        ),
    ]
