# Generated by Django 5.1.4 on 2025-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0018_vaccination_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='status',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='statuses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_names',
            field=models.JSONField(default=list),
        ),
    ]
