# Generated by Django 5.1.4 on 2025-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0018_rename_mrd_no_appointment_mrdno_consultation_mrdno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='otherRegister',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='otherRegister',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
