# Generated by Django 5.1.4 on 2025-05-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0019_dashboard_otherregister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
