# Generated by Django 5.1.4 on 2025-03-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0019_remove_vaccination_name_remove_vaccination_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventsandcamps',
        ),
    ]
