# Generated by Django 5.1.4 on 2025-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0020_employee_details_employee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='other_reason_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='transfer_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
