# Generated by Django 5.1.4 on 2025-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0020_prescription_mrdno'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(db_index=True, max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('dose_volume', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Quantity',
                'verbose_name_plural': 'Daily Quantities',
                'ordering': ['date', 'chemical_name', 'brand_name', 'expiry_date'],
                'unique_together': {('chemical_name', 'brand_name', 'dose_volume', 'expiry_date', 'date')},
            },
        ),
    ]
