# Generated by Django 5.1.4 on 2025-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0021_employee_details_other_reason_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form17',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form27',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form38',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form39',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form40',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instrumentcalibration',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
