# Generated by Django 5.1.4 on 2025-03-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0021_eventsandcamps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventsandcamps',
        ),
    ]
