# Generated by Django 5.1.4 on 2025-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0021_dailyquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
