# Generated by Django 5.1.4 on 2025-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0022_employee_details_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='docName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
