# Generated by Django 5.1.4 on 2025-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0022_form17_entry_date_form27_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessassessment',
            name='conditional_fit_feilds',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
