# Generated by Django 5.1.4 on 2025-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0023_employee_details_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='application_form/'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='consent',
            field=models.FileField(blank=True, null=True, upload_to='consent/'),
        ),
    ]
