# Generated by Django 5.1.4 on 2025-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0023_alter_fitnessassessment_conditional_fit_feilds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessassessment',
            name='conditional_fit_feilds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
