# Generated by Django 5.1.4 on 2025-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0024_delete_vaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('emp_no', models.CharField(max_length=30, unique=True)),
                ('vaccination', models.JSONField()),
            ],
        ),
    ]
