# Generated by Django 5.1.7 on 2025-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0024_alter_fitnessassessment_conditional_fit_feilds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
