# Generated by Django 5.1.4 on 2025-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0024_vitals_application_form_vitals_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
