# Generated by Django 5.1.4 on 2025-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0025_vaccinationrecord_mrdno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='calcium',
            new_name='Total_Cholesterol',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='calcium_comments',
            new_name='Total_Cholesterol_comments',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='calcium_reference_range_from',
            new_name='Total_Cholesterol_reference_range_from',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='calcium_reference_range_to',
            new_name='Total_Cholesterol_reference_range_to',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='calcium_unit',
            new_name='Total_Cholesterol_unit',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='ecg_reference_range_from',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='ecg_reference_range_to',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='ecg_unit',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='echo_reference_range_from',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='echo_reference_range_to',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='echo_unit',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='tmt_normal_reference_range_from',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='tmt_normal_reference_range_to',
        ),
        migrations.RemoveField(
            model_name='enzymescardiacprofile',
            name='tmt_normal_unit',
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='peripheral_blood_smear_others_comments',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='peripheral_blood_smear_parasites_comments',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='peripheral_blood_smear_rbc_morphology_comments',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
    ]
