# Generated by Django 5.1.4 on 2025-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0026_rename_calcium_lipidprofile_total_cholesterol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherstest',
            name='Bone_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Bone_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Bone_unit',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
    ]
