# Generated by Django 5.1.4 on 2025-06-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0027_otherstest_bone_reference_range_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherstest',
            old_name='Bone_Densitometry_comments',
            new_name='Bone_Densitometry_Densitometry_comments',
        ),
        migrations.RenameField(
            model_name='otherstest',
            old_name='Bone_reference_range_from',
            new_name='Bone_Densitometry_reference_range_from',
        ),
        migrations.RenameField(
            model_name='otherstest',
            old_name='Bone_reference_range_to',
            new_name='Bone_Densitometry_reference_range_to',
        ),
        migrations.RenameField(
            model_name='otherstest',
            old_name='Bone_unit',
            new_name='Bone_Densitometry_unit',
        ),
    ]
