# Generated by Django 5.1.7 on 2025-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0027_mockdashboard_mockemployeedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='visitOutcome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
