# Generated by Django 5.1.7 on 2025-04-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0028_dashboard_visitoutcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultated_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultated_Dr',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='submitted_Dr',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='submitted_by_nurse',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dressing',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='lotions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='powder',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='respules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='suture_procedure',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='aadhar_no',
            field=models.TextField(blank=True, default='Null', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.TextField(blank=True, default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contractor_name',
            field=models.TextField(blank=True, default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='emp_no',
            field=models.TextField(blank=True, default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employer',
            field=models.TextField(blank=True, default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mrd_no',
            field=models.TextField(blank=True, default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.TextField(blank=True, default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='organization_name',
            field=models.TextField(blank=True, default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='role',
            field=models.TextField(blank=True, default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TextField(blank=True, default='Null', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
