# Generated by Django 5.1.4 on 2025-06-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0028_rename_bone_densitometry_comments_otherstest_bone_densitometry_densitometry_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherstest',
            old_name='Bone_Densitometry_Densitometry_comments',
            new_name='Bone_Densitometry_comments',
        ),
    ]
