# Generated by Django 5.1.4 on 2025-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0029_rename_bone_densitometry_densitometry_comments_otherstest_bone_densitometry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='heamatalogy',
            name='Haemotocrit',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='Haemotocrit_comments',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='Haemotocrit_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='Haemotocrit_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='Haemotocrit_unit',
            field=models.TextField(default='NULL', max_length=255),
            preserve_default=False,
        ),
    ]
