# Generated by Django 5.1.4 on 2025-03-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0029_consultation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
