# Generated by Django 5.1.4 on 2025-04-09 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0029_remove_appointment_consultated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentcalibration',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='instrumentcalibration',
            name='freq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrumentcalibration',
            name='next_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='calibration_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='equipment_sl_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
