# Generated by Django 5.1.4 on 2025-04-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0030_remove_instrumentcalibration_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessassessment',
            options={'verbose_name': 'Fitness Assessment', 'verbose_name_plural': 'Fitness Assessments'},
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='eye_exam_fit_status',
            field=models.CharField(blank=True, choices=[('Fit', 'Fit'), ('Fit when newly prescribed glass', 'Fit when newly prescribed glass'), ('Fit with existing glass', 'Fit with existing glass'), ('Fit with an advice to change existing glass with newly prescribed glass', 'Fit with an advice to change existing glass with newly prescribed glass'), ('Unfit', 'Unfit')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='eye_exam_result',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Defective', 'Defective'), ('Color Blindness', 'Color Blindness')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='general_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='systematic_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='acrophobia',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='emp_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='overall_fitness',
            field=models.CharField(blank=True, choices=[('fit', 'Fit'), ('unfit', 'Unfit'), ('conditional', 'Conditional Fit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='romberg_test',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='tremors',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='trendelenberg_test',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
