# Generated by Django 5.1.4 on 2025-06-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0030_heamatalogy_haemotocrit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='CO_dizziness',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Claustrophobia',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Dysdiadochokinesia',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Finger_nose_test',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='MusculoSkeletal_Movements',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Nystagmus_Test',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Psychological_PMK',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Psychological_zollingar',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='Tandem',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
