# Generated by Django 5.1.4 on 2025-03-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0031_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='aadhar_no',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_no',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultated_by',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contractor_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='emp_no',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employer',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mrd_no',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='organization_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='role',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TextField(blank=True, max_length=225),
        ),
    ]
