# Generated by Django 5.1.4 on 2025-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0031_fitnessassessment_co_dizziness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiryregister',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
