# Generated by Django 5.1.4 on 2025-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0034_remove_consultation_illness_or_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='area',
            field=models.TextField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='nationality',
            field=models.TextField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='state',
            field=models.TextField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='conditional_fit_feilds',
            field=models.JSONField(blank=True, default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='bmi_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='bmi_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='diastolic_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='diastolic_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='height_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='height_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='pulse_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='pulse_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='respiratory_rate_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='respiratory_rate_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='spO2_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='spO2_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='systolic_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='systolic_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='temperature_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='temperature_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='weight_comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='weight_status',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
