# Generated by Django 5.1.4 on 2025-07-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0034_autoimmunetest_checked_coagulationtest_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alcohol_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('alcoholBreathSmell', models.CharField(blank=True, max_length=255, null=True)),
                ('speech', models.CharField(blank=True, max_length=255, null=True)),
                ('drynessOfMouth', models.CharField(blank=True, max_length=255, null=True)),
                ('drynessOfLips', models.CharField(blank=True, max_length=255, null=True)),
                ('cnsPupilReaction', models.CharField(blank=True, max_length=255, null=True)),
                ('handTremors', models.CharField(blank=True, max_length=255, null=True)),
                ('alcoholAnalyzerStudy', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalLeaveCertificateForm_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('employeeName', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('empNo', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('jswContract', models.CharField(blank=True, max_length=255, null=True)),
                ('natureOfWork', models.CharField(blank=True, max_length=255, null=True)),
                ('hasSurgicalHistory', models.CharField(blank=True, max_length=255, null=True)),
                ('covidVaccination', models.CharField(blank=True, max_length=255, null=True)),
                ('personalLeaveDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('leaveFrom', models.CharField(blank=True, max_length=255, null=True)),
                ('leaveUpTo', models.CharField(blank=True, max_length=255, null=True)),
                ('daysLeave', models.CharField(blank=True, max_length=255, null=True)),
                ('rejoiningDate', models.CharField(blank=True, max_length=255, null=True)),
                ('bp', models.CharField(blank=True, max_length=255, null=True)),
                ('pr', models.CharField(blank=True, max_length=255, null=True)),
                ('spo2', models.CharField(blank=True, max_length=255, null=True)),
                ('temp', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('ohcStaffSignature', models.CharField(blank=True, max_length=255, null=True)),
                ('individualSignature', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee_details',
            name='previousemployer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='previouslocation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
