# Generated by Django 5.1.4 on 2025-07-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0035_alcohol_form_personalleavecertificateform_form_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alcohol_form',
        ),
        migrations.DeleteModel(
            name='PersonalLeaveCertificateForm_form',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='visiting_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
