# Generated by Django 5.1.4 on 2025-03-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0035_employee_details_area_employee_details_nationality_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessAssessment',
        ),
    ]
