# Generated by Django 5.1.4 on 2025-07-08 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0036_delete_alcohol_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(blank=True, max_length=255, verbose_name='Employee Name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Sex')),
                ('empNo', models.CharField(blank=True, max_length=50, verbose_name='Employee Number')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of Certificate')),
                ('jswContract', models.CharField(blank=True, max_length=100, verbose_name='JSW Contract')),
                ('natureOfWork', models.CharField(blank=True, max_length=255, verbose_name='Nature of Work')),
                ('covidVaccination', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=10, verbose_name='Covid Vaccination')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis (Disease/Condition)')),
                ('leaveFrom', models.DateField(blank=True, null=True, verbose_name='Leave From')),
                ('leaveUpTo', models.DateField(blank=True, null=True, verbose_name='Leave Up To')),
                ('daysLeave', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Days Leave')),
                ('rejoiningDate', models.DateField(blank=True, null=True, verbose_name='Rejoining Duty On')),
                ('shift', models.CharField(blank=True, choices=[('G', 'G Shift'), ('A', 'A Shift'), ('B', 'B Shift'), ('C', 'C Shift')], max_length=5, verbose_name='Shift')),
                ('bp', models.CharField(blank=True, max_length=20, verbose_name='Blood Pressure (BP)')),
                ('pr', models.CharField(blank=True, max_length=20, verbose_name='Pulse Rate (PR)')),
                ('spo2', models.CharField(blank=True, max_length=20, verbose_name='SPO2')),
                ('temp', models.CharField(blank=True, max_length=20, verbose_name='Temperature')),
                ('certificateFrom', models.CharField(blank=True, choices=[('Govt Hospital', 'Govt Hospital'), ('ESI Hospital', 'ESI Hospital'), ('Private Hospital', 'Private Hospital')], max_length=50, verbose_name='Certificate Issued From')),
                ('note', models.TextField(blank=True, verbose_name='Note / Remarks')),
                ('ohcStaffSignature', models.CharField(blank=True, max_length=255, verbose_name='OHC Staff Signature')),
                ('individualSignature', models.CharField(blank=True, max_length=255, verbose_name='Individual Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Certificate of Fitness',
                'verbose_name_plural': 'Medical Certificates of Fitness',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalLeaveCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(blank=True, max_length=255, verbose_name='Employee Name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Sex')),
                ('empNo', models.CharField(blank=True, max_length=50, verbose_name='Employee Number')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of Certificate')),
                ('jswContract', models.CharField(blank=True, max_length=100, verbose_name='JSW / Contract')),
                ('natureOfWork', models.CharField(blank=True, max_length=255, verbose_name='Nature of Work')),
                ('hasSurgicalHistory', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Surgical & Medical History')),
                ('covidVaccination', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Covid Vaccination')),
                ('personalLeaveDescription', models.TextField(blank=True, verbose_name='Personal Leave Description')),
                ('leaveFrom', models.DateField(blank=True, null=True, verbose_name='Leave From')),
                ('leaveUpTo', models.DateField(blank=True, null=True, verbose_name='Leave Up To')),
                ('daysLeave', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Days Leave')),
                ('rejoiningDate', models.DateField(blank=True, null=True, verbose_name='Re-joining Duty On')),
                ('bp', models.CharField(blank=True, max_length=20, verbose_name='Blood Pressure (BP)')),
                ('pr', models.CharField(blank=True, max_length=20, verbose_name='Pulse Rate (PR)')),
                ('spo2', models.CharField(blank=True, max_length=20, verbose_name='SPO2')),
                ('temp', models.CharField(blank=True, max_length=20, verbose_name='Temperature')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ohcStaffSignature', models.CharField(blank=True, max_length=255, verbose_name='OHC Staff Signature')),
                ('individualSignature', models.CharField(blank=True, max_length=255, verbose_name='Individual Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Leave Certificate',
                'verbose_name_plural': 'Personal Leave Certificates',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='alcohol_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date of Test')),
                ('alcoholBreathSmell', models.CharField(blank=True, max_length=255, null=True)),
                ('speech', models.CharField(blank=True, max_length=255, null=True)),
                ('drynessOfMouth', models.CharField(blank=True, max_length=255, null=True)),
                ('drynessOfLips', models.CharField(blank=True, max_length=255, null=True)),
                ('cnsPupilReaction', models.CharField(blank=True, max_length=255, null=True)),
                ('handTremors', models.CharField(blank=True, max_length=255, null=True)),
                ('alcoholAnalyzerStudy', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_forms', to='jsw.employee_details')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
