# Generated by Django 5.1.4 on 2025-03-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0037_fitnessassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='purpose',
            field=models.TextField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='register',
            field=models.TextField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='type',
            field=models.TextField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='type_of_visit',
            field=models.TextField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsandcamps',
            name='hospital_name',
            field=models.TextField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
