# Generated by Django 5.1.4 on 2025-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0037_medicalcertificate_personalleavecertificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcohol_form',
            old_name='alcoholAnalyzerStudy',
            new_name='alcohol_analyzer_study',
        ),
        migrations.RenameField(
            model_name='alcohol_form',
            old_name='alcoholBreathSmell',
            new_name='alcohol_breath_smell',
        ),
        migrations.RenameField(
            model_name='alcohol_form',
            old_name='cnsPupilReaction',
            new_name='cns_pupil_reaction',
        ),
        migrations.RenameField(
            model_name='alcohol_form',
            old_name='drynessOfLips',
            new_name='dryness_of_lips',
        ),
        migrations.RenameField(
            model_name='alcohol_form',
            old_name='drynessOfMouth',
            new_name='dryness_of_mouth',
        ),
        migrations.RenameField(
            model_name='alcohol_form',
            old_name='handTremors',
            new_name='hand_tremors',
        ),
    ]
