# Generated by Django 5.1.4 on 2025-07-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0038_rename_alcoholanalyzerstudy_alcohol_form_alcohol_analyzer_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol_form',
            name='aadhar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='alcohol_form',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
