# Generated by Django 5.1.4 on 2025-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0038_employee_details_purpose_employee_details_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='employer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
