# Generated by Django 5.1.4 on 2025-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0039_fitnessassessment_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('tablets', models.JSONField(blank=True, null=True)),
                ('injections', models.JSONField(blank=True, null=True)),
                ('creams', models.JSONField(blank=True, null=True)),
                ('others', models.JSONField(blank=True, null=True)),
                ('submitted_by', models.CharField(max_length=50)),
                ('issued_by', models.CharField(max_length=50)),
                ('nurse_notes', models.TextField(blank=True, null=True)),
                ('emp_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
    ]
