# Generated by Django 5.1.4 on 2025-07-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0039_alcohol_form_aadhar_alcohol_form_mrdno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol_form',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of Test'),
        ),
    ]
