# Generated by Django 5.1.4 on 2025-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0040_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
