# Generated by Django 5.1.4 on 2025-07-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0040_alter_alcohol_form_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='aadhar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalleavecertificate',
            name='aadhar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='personalleavecertificate',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
