# Generated by Django 5.1.4 on 2025-07-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0041_medicalcertificate_aadhar_medicalcertificate_mrdno_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('aadhar', 'entry_date')},
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_mrd_history',
            field=models.JSONField(blank=True, default=list, help_text='A list of MRD numbers for follow-up reference.', null=True),
        ),
    ]
