# Generated by Django 5.1.4 on 2025-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0042_alter_consultation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimmunetest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coagulationtest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ctreport',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='culturesensitivitytest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heamatalogy',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='menspack',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='motiontest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='occupationalprofile',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ophthalmicreport',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routinesugartests',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serologytest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thyroidfunctiontest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='urineroutinetest',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='womenspack',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xray',
            name='mrdNo',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
