# Generated by Django 5.1.4 on 2025-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0043_autoimmunetest_mrdno_coagulationtest_mrdno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='follow_up_mrd_history',
            field=models.JSONField(blank=True, default=list, help_text='A list of MRD numbers for follow-up reference.', null=True),
        ),
    ]
