# Generated by Django 5.1.4 on 2025-07-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0044_fitnessassessment_follow_up_mrd_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='ldl_hdl_ratio',
            new_name='ldl_chol_hdl_chol_ratio',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='ldl_hdl_ratio_comments',
            new_name='ldl_chol_hdl_chol_ratio_comments',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='ldl_hdl_ratio_reference_range_from',
            new_name='ldl_chol_hdl_chol_ratio_reference_range_from',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='ldl_hdl_ratio_reference_range_to',
            new_name='ldl_chol_hdl_chol_ratio_reference_range_to',
        ),
        migrations.RenameField(
            model_name='lipidprofile',
            old_name='ldl_hdl_ratio_unit',
            new_name='ldl_chol_hdl_chol_ratio_unit',
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='angiogram',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enzymescardiacprofile',
            name='angiogram_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='C_reactive_protien',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='C_reactive_protien_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='C_reactive_protien_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='C_reactive_protien_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='C_reactive_protien_unit',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Clonoscopy',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Clonoscopy_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Endoscopy',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Endoscopy_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Serum_Ferritin',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Serum_Ferritin_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Serum_Ferritin_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Serum_Ferritin_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Serum_Ferritin_unit',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Urethroscopy',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Urethroscopy_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_B12',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_B12_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_B12_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_B12_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_B12_unit',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_D',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_D_comments',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_D_reference_range_from',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_D_reference_range_to',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Vit_D_unit',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
