# Generated by Django 5.1.4 on 2025-07-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0045_rename_ldl_hdl_ratio_lipidprofile_ldl_chol_hdl_chol_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='permanent_nationality',
            new_name='permanent_country',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='residential_nationality',
            new_name='residential_country',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='reason',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='bp_sugar_chart_reason',
            field=models.CharField(blank=True, help_text='Reason for BP Sugar Chart', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='followup_other_reason',
            field=models.TextField(blank=True, help_text="Text for 'Other' reason in Follow Up"),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='followup_reason',
            field=models.CharField(blank=True, help_text='Reason for Follow Up Visit', max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='bp_sugar_chart_reason',
            field=models.CharField(blank=True, help_text='Reason for BP Sugar Chart', max_length=255),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='followup_other_reason',
            field=models.TextField(blank=True, help_text="Text for 'Other' reason in Follow Up"),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='followup_reason',
            field=models.CharField(blank=True, help_text='Reason for Follow Up Visit', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='emp_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='register',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='status',
            field=models.CharField(blank=True, help_text='Patient status for BP Sugar Check', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='type_of_visit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='status',
            field=models.CharField(blank=True, help_text='Patient status for BP Sugar Check', max_length=255),
        ),
    ]
