# Generated by Django 5.1.4 on 2025-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0046_rename_permanent_nationality_employee_details_permanent_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='submittedNurse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='submittedNurse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
