# Generated by Django 5.1.4 on 2025-07-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0047_consultation_submittednurse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='bookedDoctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='bookedDoctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
