# Generated by Django 5.1.4 on 2025-07-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0048_consultation_bookeddoctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstrumentCalibration',
        ),
    ]
