# Generated by Django 5.1.4 on 2025-07-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0049_delete_instrumentcalibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_sl_no', models.CharField(max_length=255, unique=True)),
                ('serial_no', models.IntegerField(editable=False)),
                ('entry_date', models.DateField(auto_now=True)),
                ('instrument_name', models.CharField(max_length=255)),
                ('numbers', models.IntegerField()),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('freq', models.CharField(blank=True, max_length=255, null=True)),
                ('calibration_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('calibration_status', models.BooleanField()),
                ('done_by', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
