# Generated by Django 5.1.4 on 2025-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0050_instrumentcalibration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='calibration_status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
