# Generated by Django 5.1.4 on 2025-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0051_alter_instrumentcalibration_calibration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='equipment_sl_no',
            field=models.CharField(max_length=255),
        ),
    ]
