# Generated by Django 5.1.4 on 2025-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0052_alter_instrumentcalibration_equipment_sl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcalibration',
            name='instrument_cnodition',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
