# Generated by Django 5.1.4 on 2025-07-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0054_remove_instrumentcalibration_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcalibration',
            name='inst_status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
