# Generated by Django 5.1.4 on 2025-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0055_instrumentcalibration_inst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
