# Generated by Django 5.1.4 on 2025-08-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0056_member_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentcalibration',
            name='serial_no',
        ),
    ]
