# Generated by Django 5.1.4 on 2025-08-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0057_remove_instrumentcalibration_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcalibration',
            name='instrument_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
