# Generated by Django 5.1.4 on 2025-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0058_instrumentcalibration_instrument_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctreport',
            name='CT_Chest',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Chest_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Head',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Head_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Lower_limb',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Lower_limb_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Neck',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Neck_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Upper_limb',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctreport',
            name='CT_Upper_limb_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Chest',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Chest_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Head',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Head_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Lower_limb',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Lower_limb_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Neck',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Neck_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Upper_limb',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='mri_Upper_limb_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Bronchoscopy',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Bronchoscopy_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Cystoscopy',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Cystoscopy_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Hysteroscopy',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Hysteroscopy_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Ureteroscopy',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstest',
            name='Ureteroscopy_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xray',
            name='Lower_limb',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xray',
            name='Lower_limb_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xray',
            name='Skull',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xray',
            name='Skull_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xray',
            name='Upper_limb',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xray',
            name='Upper_limb_comments',
            field=models.TextField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
