# Generated by Django 5.1.4 on 2025-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0059_ctreport_ct_chest_ctreport_ct_chest_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
