# Generated by Django 5.1.4 on 2025-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0060_alter_instrumentcalibration_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
