# Generated by Django 5.1.4 on 2025-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0061_alter_instrumentcalibration_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcalibration',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
