# Generated by Django 5.1.4 on 2025-08-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0062_alter_instrumentcalibration_calibration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t3_comments',
            new_name='t3_triiodothyronine_comments',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t3_reference_range_from',
            new_name='t3_triiodothyronine_reference_range_from',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t3_reference_range_to',
            new_name='t3_triiodothyronine_reference_range_to',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t3_unit',
            new_name='t3_triiodothyronine_unit',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t4_comments',
            new_name='t4_thyroxine_comments',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t4_reference_range_from',
            new_name='t4_thyroxine_reference_range_from',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t4_reference_range_to',
            new_name='t4_thyroxine_reference_range_to',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='t4_unit',
            new_name='t4_thyroxine_unit',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='tsh_comments',
            new_name='tsh_thyroid_stimulating_hormone_comments',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='tsh_reference_range_from',
            new_name='tsh_thyroid_stimulating_hormone_reference_range_from',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='tsh_reference_range_to',
            new_name='tsh_thyroid_stimulating_hormone_reference_range_to',
        ),
        migrations.RenameField(
            model_name='thyroidfunctiontest',
            old_name='tsh_unit',
            new_name='tsh_thyroid_stimulating_hormone_unit',
        ),
    ]
