# Generated by Django 3.2.22 on 2025-10-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0063_rename_t3_comments_thyroidfunctiontest_t3_triiodothyronine_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='contractor_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, db_column='password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default='default123', max_length=50),
        ),
    ]
