# Generated by Django 5.1.4 on 2025-11-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0064_auto_20251017_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
