# Generated by Django 5.1.4 on 2025-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0065_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('job_nature', models.CharField(blank=True, max_length=255)),
                ('date_exited', models.DateField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
