# Generated by Django 5.2 on 2025-12-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0066_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='division',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='workarea',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
