# Generated by Django 5.1.4 on 2025-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0067_employee_details_division_employee_details_workarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='significantnotes',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
